FROM petronetto/docker-python-deep-learning:v-23
LABEL maintainer="luk.zim91@gmail.com"

COPY . /tmp/pht
RUN cd /tmp/pht && \
    python ./run_tests.py && \
    python setup.py install && \
    cd /home/notebooks && \
    rm -rf /tmp/* /var/tmp/* && sync

